services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data

volumes:
  postgres:
    name: graphql-sample-postgres
